//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tMax14.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://odemeler.garanti.com.tr/", ConfigurationName="ServiceReference1.FirmAccountActivitySoap")]
    public interface FirmAccountActivitySoap {
        
        // CODEGEN: Generating message contract since the operation FirmAccountActivity is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://odemeler.garanti.com.tr/services/FirmAccountActivitySoap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        tMax14.ServiceReference1.FirmAccountActivityResponse1 FirmAccountActivity(tMax14.ServiceReference1.FirmAccountActivityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://odemeler.garanti.com.tr/services/FirmAccountActivitySoap", ReplyAction="*")]
        System.Threading.Tasks.Task<tMax14.ServiceReference1.FirmAccountActivityResponse1> FirmAccountActivityAsync(tMax14.ServiceReference1.FirmAccountActivityRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://odemeler.garanti.com.tr/")]
    public partial class FirmAccountActivity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SecureToken securetokenField;
        
        private string firmCodeField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string branchNumField;
        
        private string accountNumField;
        
        private string iBANField;
        
        private string transactionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SecureToken securetoken {
            get {
                return this.securetokenField;
            }
            set {
                this.securetokenField = value;
                this.RaisePropertyChanged("securetoken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string FirmCode {
            get {
                return this.firmCodeField;
            }
            set {
                this.firmCodeField = value;
                this.RaisePropertyChanged("FirmCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string BranchNum {
            get {
                return this.branchNumField;
            }
            set {
                this.branchNumField = value;
                this.RaisePropertyChanged("BranchNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string AccountNum {
            get {
                return this.accountNumField;
            }
            set {
                this.accountNumField = value;
                this.RaisePropertyChanged("AccountNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
                this.RaisePropertyChanged("IBAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odemeler.garanti.com.tr/")]
    public partial class SecureToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string passwordField;
        
        private string createTimestampField;
        
        private string encodedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CreateTimestamp {
            get {
                return this.createTimestampField;
            }
            set {
                this.createTimestampField = value;
                this.RaisePropertyChanged("CreateTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Encoded {
            get {
                return this.encodedField;
            }
            set {
                this.encodedField = value;
                this.RaisePropertyChanged("Encoded");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odemeler.garanti.com.tr/")]
    public partial class AccountActivityDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string activityDateField;
        
        private string amountField;
        
        private string balanceField;
        
        private string explanationField;
        
        private string transactionIdField;
        
        private string transactionReferenceIdField;
        
        private string corrBankNumField;
        
        private string corrBranchNumField;
        
        private string corrIBANField;
        
        private string corrVKNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ActivityDate {
            get {
                return this.activityDateField;
            }
            set {
                this.activityDateField = value;
                this.RaisePropertyChanged("ActivityDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Explanation {
            get {
                return this.explanationField;
            }
            set {
                this.explanationField = value;
                this.RaisePropertyChanged("Explanation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string TransactionReferenceId {
            get {
                return this.transactionReferenceIdField;
            }
            set {
                this.transactionReferenceIdField = value;
                this.RaisePropertyChanged("TransactionReferenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string CorrBankNum {
            get {
                return this.corrBankNumField;
            }
            set {
                this.corrBankNumField = value;
                this.RaisePropertyChanged("CorrBankNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string CorrBranchNum {
            get {
                return this.corrBranchNumField;
            }
            set {
                this.corrBranchNumField = value;
                this.RaisePropertyChanged("CorrBranchNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string CorrIBAN {
            get {
                return this.corrIBANField;
            }
            set {
                this.corrIBANField = value;
                this.RaisePropertyChanged("CorrIBAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string CorrVKN {
            get {
                return this.corrVKNField;
            }
            set {
                this.corrVKNField = value;
                this.RaisePropertyChanged("CorrVKN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://odemeler.garanti.com.tr/")]
    public partial class FirmAccountDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNameField;
        
        private string accountTypeField;
        
        private string branchNumField;
        
        private string accountNumField;
        
        private string currencyCodeField;
        
        private string iBANField;
        
        private string openDateField;
        
        private string lastActivityDateField;
        
        private string balanceField;
        
        private string blockedAmountField;
        
        private string availableBalanceField;
        
        private string creditLimitField;
        
        private string availableBalanceWithCreditField;
        
        private AccountActivityDetail[] accountActivitiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
                this.RaisePropertyChanged("AccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string BranchNum {
            get {
                return this.branchNumField;
            }
            set {
                this.branchNumField = value;
                this.RaisePropertyChanged("BranchNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string AccountNum {
            get {
                return this.accountNumField;
            }
            set {
                this.accountNumField = value;
                this.RaisePropertyChanged("AccountNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("CurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
                this.RaisePropertyChanged("IBAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string OpenDate {
            get {
                return this.openDateField;
            }
            set {
                this.openDateField = value;
                this.RaisePropertyChanged("OpenDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string LastActivityDate {
            get {
                return this.lastActivityDateField;
            }
            set {
                this.lastActivityDateField = value;
                this.RaisePropertyChanged("LastActivityDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string BlockedAmount {
            get {
                return this.blockedAmountField;
            }
            set {
                this.blockedAmountField = value;
                this.RaisePropertyChanged("BlockedAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string AvailableBalance {
            get {
                return this.availableBalanceField;
            }
            set {
                this.availableBalanceField = value;
                this.RaisePropertyChanged("AvailableBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string CreditLimit {
            get {
                return this.creditLimitField;
            }
            set {
                this.creditLimitField = value;
                this.RaisePropertyChanged("CreditLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string AvailableBalanceWithCredit {
            get {
                return this.availableBalanceWithCreditField;
            }
            set {
                this.availableBalanceWithCreditField = value;
                this.RaisePropertyChanged("AvailableBalanceWithCredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AccountActivities", IsNullable=true, Order=13)]
        public AccountActivityDetail[] AccountActivities {
            get {
                return this.accountActivitiesField;
            }
            set {
                this.accountActivitiesField = value;
                this.RaisePropertyChanged("AccountActivities");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://odemeler.garanti.com.tr/")]
    public partial class FirmAccountActivityResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnValField;
        
        private string messageTextField;
        
        private string currentDateTimeField;
        
        private string customerNumField;
        
        private FirmAccountDetail[] firmAccountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ReturnVal {
            get {
                return this.returnValField;
            }
            set {
                this.returnValField = value;
                this.RaisePropertyChanged("ReturnVal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
                this.RaisePropertyChanged("MessageText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string CurrentDateTime {
            get {
                return this.currentDateTimeField;
            }
            set {
                this.currentDateTimeField = value;
                this.RaisePropertyChanged("CurrentDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string CustomerNum {
            get {
                return this.customerNumField;
            }
            set {
                this.customerNumField = value;
                this.RaisePropertyChanged("CustomerNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FirmAccounts", IsNullable=true, Order=4)]
        public FirmAccountDetail[] FirmAccounts {
            get {
                return this.firmAccountsField;
            }
            set {
                this.firmAccountsField = value;
                this.RaisePropertyChanged("FirmAccounts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirmAccountActivityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://odemeler.garanti.com.tr/", Order=0)]
        public tMax14.ServiceReference1.FirmAccountActivity FirmAccountActivity;
        
        public FirmAccountActivityRequest() {
        }
        
        public FirmAccountActivityRequest(tMax14.ServiceReference1.FirmAccountActivity FirmAccountActivity) {
            this.FirmAccountActivity = FirmAccountActivity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirmAccountActivityResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://odemeler.garanti.com.tr/", Order=0)]
        public tMax14.ServiceReference1.FirmAccountActivityResponse FirmAccountActivityResponse;
        
        public FirmAccountActivityResponse1() {
        }
        
        public FirmAccountActivityResponse1(tMax14.ServiceReference1.FirmAccountActivityResponse FirmAccountActivityResponse) {
            this.FirmAccountActivityResponse = FirmAccountActivityResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FirmAccountActivitySoapChannel : tMax14.ServiceReference1.FirmAccountActivitySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirmAccountActivitySoapClient : System.ServiceModel.ClientBase<tMax14.ServiceReference1.FirmAccountActivitySoap>, tMax14.ServiceReference1.FirmAccountActivitySoap {
        
        public FirmAccountActivitySoapClient() {
        }
        
        public FirmAccountActivitySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirmAccountActivitySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirmAccountActivitySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirmAccountActivitySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tMax14.ServiceReference1.FirmAccountActivityResponse1 tMax14.ServiceReference1.FirmAccountActivitySoap.FirmAccountActivity(tMax14.ServiceReference1.FirmAccountActivityRequest request) {
            return base.Channel.FirmAccountActivity(request);
        }
        
        public tMax14.ServiceReference1.FirmAccountActivityResponse FirmAccountActivity(tMax14.ServiceReference1.FirmAccountActivity FirmAccountActivity1) {
            tMax14.ServiceReference1.FirmAccountActivityRequest inValue = new tMax14.ServiceReference1.FirmAccountActivityRequest();
            inValue.FirmAccountActivity = FirmAccountActivity1;
            tMax14.ServiceReference1.FirmAccountActivityResponse1 retVal = ((tMax14.ServiceReference1.FirmAccountActivitySoap)(this)).FirmAccountActivity(inValue);
            return retVal.FirmAccountActivityResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<tMax14.ServiceReference1.FirmAccountActivityResponse1> tMax14.ServiceReference1.FirmAccountActivitySoap.FirmAccountActivityAsync(tMax14.ServiceReference1.FirmAccountActivityRequest request) {
            return base.Channel.FirmAccountActivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<tMax14.ServiceReference1.FirmAccountActivityResponse1> FirmAccountActivityAsync(tMax14.ServiceReference1.FirmAccountActivity FirmAccountActivity) {
            tMax14.ServiceReference1.FirmAccountActivityRequest inValue = new tMax14.ServiceReference1.FirmAccountActivityRequest();
            inValue.FirmAccountActivity = FirmAccountActivity;
            return ((tMax14.ServiceReference1.FirmAccountActivitySoap)(this)).FirmAccountActivityAsync(inValue);
        }
    }
}
